baseURL: "https://alainbouchard.github.io/"
languageCode: "en-us"
title: "Alain Bouchard's Engineering Notes"
theme: "hugo-theme-learn"
module:
  - imports:
    - disable : false
      path: github.com/AlainBouchard/engineering-notes
      lang: en
      mounts:
      - source: .
        target: content
  - mounts:
    - source: content/README.md
      target: content/_index.md
params:
   themeVariant: "blue"
