baseURL = "https://alainbouchard.github.io/"
languageCode = "en-us"
title = "Alain Bouchard's Engineering Notes"
theme = "hugo-theme-learn"

[[module]]
[[module.imports]]
path = "github.com/AlainBouchard/engineering-notes"

  [[module.imports.mounts]]
  source = "content"
  target = "content"

[params]
themeVariant = "blue"
