baseURL = "https://AlainBouchard.github.io/"
languageCode = "en-us"
title = "Alain Bouchard's Engineering Notes"
theme = "hugo-theme-relearn"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[module]

  [[module.imports]]
    path = "github.com/AlainBouchard/engineering-notes"

    [[module.imports.mounts]]
      source = "content"
      target = "content"
